[project]
name = "evals"
version = "1.0.3.post1"
requires-python = ">=3.9"
dependencies = [
    "mypy",
    "openai == 0.28.1",
    "tiktoken",
    "blobfile",
    "backoff",
    "numpy",
    "snowflake-connector-python[pandas]",
    "pandas",
    "datasets",
    "fire",
    "pydantic",
    "tqdm",
    "nltk",
    "filelock",
    "mock",
    "langdetect",
    'termcolor',
    "lz4",
    "pyzstd",
    "pyyaml",
    "sacrebleu",
    "matplotlib",
    "pytest",
    "langchain",
    "types-PyYAML",
    "spacy-universal-sentence-encoder",
    "jiwer",
]

[project.optional-dependencies]
formatters = [
    "black",
    "isort",
    "autoflake",
    "ruff"
]

[project.scripts]
oaieval = "evals.cli.oaieval:main"
oaievalset = "evals.cli.oaievalset:main"

[tool.setuptools]
packages = ["evals"]

[tool.ruff]
# Allow lines to be as long as 767 characters, this is currently the longest line
# TODO: This should be brought down in the future
line-length = 767
